{{ if .Values.application.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: marker-secret
  labels:
    {{- include "marker.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.application.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
